package com.smartwms.constants;

/**
 * Types of events tracked for product audit trail.
 */
public enum AuditEventType {
    PRODUCT_CREATED,
    PRODUCT_UPDATED,
    PRODUCT_DELETED,
    PRODUCT_RESTORED,
    PRODUCT_ACTIVATED,
    PRODUCT_DEACTIVATED,
    PRODUCT_STOCK_ADJUSTED,
    PRODUCT_STOCK_RESERVED,
    PRODUCT_STOCK_RELEASED,
    PRODUCT_DISPATCHED,
    PRODUCT_STATUS_CHANGED,
    PRODUCT_CATEGORY_CHANGED,
    PRODUCT_SUPPLIER_CHANGED,
    PRODUCT_WAREHOUSE_CHANGED
}
